title: SheetHappens!
description: Free Excel Sheets for work, fun and life
baseurl: ""
url: "https://www.sheethappens.com"
theme: minima
author: Francesco Palanza
lang: en
google_analytics: G-M7JF39LV16
header_pages:
- about.md
- submit.md
